### ISSUE TITLE
Error: spawn docker-compose ENOENT

### ISSUE THREAD

**Issue by amitojsingh366** [PDMLab/docker-compose#173]
```
Error: spawn docker-compose ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn docker-compose',
  path: 'docker-compose',
  spawnargs: [ 'down' ]
}
```

**Comment by Steveb-p** [comment]
Hi @amitojsingh366.

Could you give some context please and specify what isn't working for you / what happened?

**Comment by amitojsingh366** [comment]
i just realized that the directory i was trying to run this in didn't exist. my bad this isn't a valid issue
